### ISSUE TITLE
If tablet crashes during buy transaction, the BTC will not be sent like in Gen 1

### ISSUE THREAD

**Issue by voidhole** [lamassu/lamassu-server#148]
If table reboot itself during a buy transaction, the btc will not be sent. It will remains as pending in the GUI.

**Comment by naconner** [comment]
Unlike the legacy version, the current machine will not send partial batches for the bills it already knows about prior to a disconnect. That caused more issues than it solved by complicating transaction records and increasing user frustration when it appeared they were shortchanged. 

On both versions, if the network instead goes down during a transaction, the transaction is attempted again if the machine regains the connection (unless powered off or before the next periodic lamassu-machine restart).

If the lamassu-machine process restarts or the tablet is rebooted, then both on the legacy version as well as the current versions, it won't attempt to resend the transaction.

That's in order to avoid a machine losing power during a transaction, coins being manually fulfilled by the operator in the meantime, and then the transaction being automatically resent once the machine is turned back on (resulting in a double-send).

In the upcoming admin, we'll have status indicators for particular transactions that require attention.
